name: Rust

on:
  push:
    tags: 'v*.*.*'
  workflow_dispatch:

jobs:
  build-release:
    name: build-release
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: '1.76.0'
          profile: minimal
          override: true

      - name: Run tests
        run: cargo test

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event_name == 'workflow_dispatch' && '' || github.ref }}
          release_name: Release ${{ github.event_name == 'workflow_dispatch' && 'main' || github.ref }}
          draft: true
          prerelease: false
